src/Entity/User.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{   
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="user", orphanRemoval=true)
     */
    private $Article;


    /**
     * @ORM\OneToOne(targetEntity=Avatar::class, cascade={"persist", "remove"})
     */
    private $Avatar;



    public function __construct()
    {
        $this->Article = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        if ($firstname === null) {
            $firstname = 'unknown';
        }
        $this->firstname = $firstname;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        if($name === null){
            $name = 'unknown';
        }
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticle(): Collection
    {
        return $this->Article;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->Article->contains($article)) {
            $this->Article[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->Article->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }
    
    public function getAvatar(): ?Avatar
    {
        return $this->Avatar;
    }

    public function setAvatar(?Avatar $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }
    public function removeFile()
    {
        if ($this->Avatar && $this->Avatar->getImageFile()) {
            $this->Avatar->setImageFile(null);
        }
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Washington Post{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
                <link rel="stylesheet" href="{{asset('css/style.css')}}">
        {% endblock %}
      
    </head>
    <header>

    {# ------profile modal------ #}
     {% if app.user %}
    <div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title mx-auto" id="exampleModalLabel">{% if app.user %}{{app.user.firstname}} {% endif %}profile</h1>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <div class="modal-body">

         {# ------card inside modal------ #}
           
                <div class="card mb-3">
                    <h3 class="card-header text-center">{{app.user.firstname}} {{app.user.name}}</h3>
                    <div class="card-body">
                        {% if (is_granted('ROLE_EDITOR')) %}
                            <h3 class="text-center">ROLE : <span class="roleLabel">EDITOR</span></h3>
                        {% endif %}
                    </div>
                    <div class="d-flex justify-content-center">
                        <img src="{{ vich_uploader_asset(app.user.avatar, 'imageFile')}}" alt="avatar_picture">
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item text-center">{{app.user.email}}</li>
                    </ul>
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{app.user.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
                <div class="modal-footer mb-4">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="{{path('profile', {'id': app.user.id})}}"><button type="button" class="btn btn-primary">Edit profile</button></a>
                </div>
            
            </div>
        </div>
    </div>
    {% endif %}
    {# ------admin modal------ #}

    <div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header bg-light d-flex justify-content-center">
                    <h1 class="modal-title text-center " id="exampleModalLabel">Admin Pannel</h1>
                </div>
            <div class="modal-body d-flex justify-content-center">    
                <a href="{{ path('admin_users')}}" ><button class="button-13 adminButton">USERS LIST</button></a>
                <a href="{{ path('article_list')}}" ><button class="button-13 adminButton">ARTICLE LIST</button></a>
               
            </div>
                <div class="modal-footer mb-4 bg-light">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            
            </div>
        </div>
    </div>



    {# ------navbar------- #}
        <nav class="navbar navbar-expand-lg bg-light fixed-top" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ path('home')}}" >Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ path('gallery')}}">Articles
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>

                        {# Rollup menu for editor roles to manage the articles #}

                        {% if is_granted('ROLE_EDITOR') %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Editor</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ path('article_list')}}">Article list</a>
                                <a class="dropdown-item" href="{{ path('article_myArticles')}}">My Articles</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ path('article_create')}}">New Article</a>
                            </div>
                        </li>
                        {% endif %}
                    </ul>
                  
                 
                 {# Navbar buttons, different depending on the roles & user adress, link  to profile modale  #}

                    <div class="rightNavBar">
                        {% if app.user == false %}
                        <a href="{{ path('app_login')}}" class="text-decoration-none text-black" ><button class="button-13">LOG IN</button></a>
                        <a href="{{ path('register')}}" class="text-decoration-none text-black"><button class="button-13">SIGN IN</button></a>
                        {% endif %}

                        {% if app.user %}
                            <div class="rightNavBar">
                                You are logged in as 
                                <span class="linkAdress">
                                    <a  class="adress" data-toggle="modal" data-target="#profileModal">
                                    {{ app.user.userIdentifier }}
                                    </a>
                                </span>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <a href="#" data-toggle="modal" data-target="#adminModal" class="text-decoration-none text-black"><button  class="button-13">ADMIN</button></a>
                                {% endif %}
                                <a href="{{ path('app_logout') }}" class="text-decoration-none text-black"><button class="button-13">LOG OUT</button></a>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="headerBox">
         <img src="{{ asset('images/app/washington_post.png') }}" alt="washington_post" class="washPostLogo">
    </div>
    
    {% block body %}
    
    {% endblock %}

    {% block javascripts %}
    {% endblock %}
    <script src="{{ asset('js/form.js') }}"></script>
    
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js'></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</html>